### ISSUE TITLE
The client page doesn't show any streams

### ISSUE THREAD

**Issue by tcsabina** [PrateekAdhikaree/streamy#26]
I have a feeling that this part of the project was never finished. (Those mock-ups in the readme makes me think that.)

But I might be mistaken, and this should work... I am not sure.

Anyhow,
I can see the stream listed at http://<server-ip>:8000/admin/streams, so the node-media-server part is properly running, but the client page (http://<server-ip>:3000/) doesn't list the streams.

Additionally, I don't see the Login button on the client page.

**Comment by PrateekAdhikaree** [comment]
Hi @tcsabina, the mockups are just that - mockups and not actual screenshots from the running project. This project was running the last time I checked, but it has been a while.

Did you create a new stream? The client would not list streams unless it has been created.

**Comment by tcsabina** [comment]
Hi Prateek!

I did not create a stream with the client, so to speak. 
I am running OBS on a test PC, and it is configured to publish the stream to the RTMP-Server. Which seems to work fine, as on the Admin-Panel of the Node-Media-Server I can see the stream is active.


Based on your mockups, the 'create stream' should be only possible if the user logged in.
But I see no Login button on the client page.

**Comment by PrateekAdhikaree** [comment]
Apologies for the late response - was caught up with a few other things. I just ran my react client and see a "Sign In with Google" on the top right of the page. Clicking it lets me login with Google and I see the "Create Streams" button. Do you not see this?

**Comment by PrateekAdhikaree** [comment]
Closing due to no response for over 6 months.
